baseURL = "https://fubira.github.io/"
languageCode = "ja-JP"
defaultContentLanguage = "ja"
title = "Empty"
copyright = "Copyright &copy; 2020 - fubira"
theme= "hugo-kiera"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "fubira"           #Author name
    github = "fubira"         #Github username
    gitlab = ""         #Gitlab username
    linkedin = ""       #LinkedIn username
    facebook = ""       #Facebook username
    twitter = "fubira"        #Twitter username
    instagram = ""      #Instagram username
    stackoverflow = ""  #StackOverflow username

[params]
    tagline = "中身のない, からっぽ, 無意味な, 当てにならない, 空虚な, くだらない;"

[params.assets]
    customCSS = ["/css/custom.css"]  #Optional Customised CSS
