baseURL = "https://fubira.github.io/"
languageCode = "ja-JP"
defaultContentLanguage = "ja"
title = "empty"
copyright = "Copyright &copy; 2020 - Author Name"
theme= "hugo-kiera"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "fubira"           #Author name
    github = "fubira"         #Github username
    gitlab = ""         #Gitlab username
    linkedin = ""       #LinkedIn username
    facebook = ""       #Facebook username
    twitter = "fubira"        #Twitter username
    instagram = ""      #Instagram username
    stackoverflow = ""  #StackOverflow username

[params]
    tagline = "the tagline for this website"
    customCSS = []  #Optional Customised CSS
